specieslist: ["Homo_sapiens","Gorilla_gorilla","Gallus_gallus",
                     "Macaca_mulatta","Monodelphis_domestica","Mus_musculus",
                     "Ornithorhynchus_anatinus","Pan_paniscus",
                     "Pan_troglodytes","Pongo_pygmaeus","Bos_taurus",
                     "Rattus_norvegicus","Anolis_carolinensis",
                     "Xenopus_tropicalis","Tetraodon_nigroviridis",
                     "Sus_scrofa","Ciona_intestinalis","Danio_rerio",
                     "Tupaia_belangeri","Callithrix_jacchus",
                     "Oryctolagus_cuniculus","Drosophila_melanogaster"]


hg38_star_index_gencode: "/home/rcf-40/amalthom/panases_soft/RNA_seq/ref_genomes/hg38/STAR_index/gencode/gencode.v28.hg38.p12"
hg38_gtf_gencode: "/panfs/cmb-panasas2/amalthom/software/genomes/gtf/human/gencode.v28.GRCh38.p12.gtf"
hg38_bed_gencode: "/panfs/cmb-panasas2/amalthom/software/genomes/gtf/human/gtfbed/gencode.v28.GRCh38.p12.bed6.bed"
mm10_star_index_gencode: "/home/rcf-40/amalthom/panases_soft/RNA_seq/scRNAseq/cellranger_2.2.0_Index/gencode.M18.mm10.p6/star"
mm10_gtf_gencode: "/panfs/cmb-panasas2/amalthom/software/genomes/gtf/mouse/gencode.vM18.mm10.p6.annotation.gtf"
mm10_bed_gencode: "/panfs/cmb-panasas2/amalthom/software/genomes/gtf/mouse/gtfbed/gencode.vM18.mm10.p6.annotation.bed"
hg19_star_index: "/home/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/hg19/STAR_index"
hg19_gtf: "/home/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/hg19/bowtie_index/hg19_.gtf"
hg19_bed: "/panfs/cmb-panasas2/amalthom/software/genomes/gtf/human/gtfbed/hg19_.gtf.bed"


Homo_sapiens_star_index: "/home/rcf-40/amalthom/panfs/software/RNA_seq/ref_genomes/species/Homo_sapiens"
Mus_musculus_star_index: "/home/rcf-40/amalthom/panfs/software/RNA_seq/ref_genomes/species/Mus_musculus"
Gallus_gallus_star_index : "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Gallus_gallus"
Gorilla_gorilla_star_index : "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Gorilla_gorilla"
Macaca_mulatta_star_index : "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Macaca_mulatta"
Monodelphis_domestica_star_index : "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Monodelphis_domestica"
Ornithorhynchus_anatinus_star_index : "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Ornithorhynchus_anatinus"
Pan_paniscus_star_index : "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Pan_paniscus"
Pan_troglodytes_star_index : "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Pan_troglodytes"
Pongo_pygmaeus_star_index : "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Pongo_abelii"
Ciona_intestinalis_star_index : "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Ciona_intestinalis"
Danio_rerio_star_index: "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Danio_rerio"
Sus_scrofa_star_index: "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Sus_scrofa"
Tupaia_belangeri_star_index: "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Tupaia_belangeri"
Callithrix_jacchus_star_index: "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Callithrix_jacchus"
Rattus_norvegicus_star_index: "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Rattus_norvegicus"
Oryctolagus_cuniculus_star_index: "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Oryctolagus_cuniculus"
Bos_taurus_star_index: "/panfs/cmb-panasas2/amalthom/software/RNA_seq/ref_genomes/species/Bos_taurus"
Anolis_carolinensis_star_index: "/home/rcf-40/amalthom/panases_soft/RNA_seq/ref_genomes/species/Anolis_carolinensis"
Xenopus_tropicalis_star_index: "/home/rcf-40/amalthom/panases_soft/RNA_seq/ref_genomes/species/Xenopus_tropicalis"
Tetraodon_nigroviridis_star_index: "/home/rcf-40/amalthom/panases_soft/RNA_seq/ref_genomes/species/Tetraodon_nigroviridis"
Drosophila_melanogaster_star_index: "/home/rcf-40/amalthom/panases_soft/RNA_seq/ref_genomes/species/Drosophila_melanogaster"

Homo_sapiens_gtf : "/panfs/cmb-panasas2/amalthom/software/genomes/species/Homo_sapiens.GRCh38.94.chr.gtf"
Mus_musculus_gtf : "/panfs/cmb-panasas2/amalthom/software/genomes/species/Mus_musculus.GRCm38.94.chr.gtf"
Gallus_gallus_gtf : "/panfs/cmb-panasas2/amalthom/software/genomes/species/Gallus_gallus.Gallus_gallus-5.0.94.chr.gtf"
Gorilla_gorilla_gtf : "/panfs/cmb-panasas2/amalthom/software/genomes/species/Gorilla_gorilla.gorGor4.94.chr.gtf"
Macaca_mulatta_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Macaca_mulatta.Mmul_8.0.1.94.chr.gtf"
Monodelphis_domestica_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Monodelphis_domestica.monDom5.94.chr.gtf"
Ornithorhynchus_anatinus_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Ornithorhynchus_anatinus.OANA5.94.gtf"
Pan_paniscus_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Pan_paniscus.panpan1.1.94.chr.gtf"
Pan_troglodytes_gtf : "/panfs/cmb-panasas2/amalthom/software/genomes/species/Pan_troglodytes.Pan_tro_3.0.94.chr.gtf"
Pongo_pygmaeus_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Pongo_abelii.PPYG2.94.chr.gtf"
Ciona_intestinalis_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Ciona_intestinalis.KH.94.gtf"
Danio_rerio_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Danio_rerio.GRCz11.94.gtf"
Sus_scrofa_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Sus_scrofa.Sscrofa11.1.94.gtf"
Tupaia_belangeri_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Tupaia_belangeri.TREESHREW.94.gtf"
Callithrix_jacchus_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Callithrix_jacchus.ASM275486v1.94.gtf"
Rattus_norvegicus_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Rattus_norvegicus.Rnor_6.0.94.chr.gtf"
Oryctolagus_cuniculus_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Oryctolagus_cuniculus.OryCun2.0.94.gtf"
Bos_taurus_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Bos_taurus.UMD3.1.94.chr.gtf"
Anolis_carolinensis_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Anolis_carolinensis.AnoCar2.0.96.gtf"
Xenopus_tropicalis_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Xenopus_tropicalis.JGI_4.2.96.gtf"
Tetraodon_nigroviridis_gtf: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Tetraodon_nigroviridis.TETRAODON8.96.gtf"
Drosophila_melanogaster_gtf: "/auto/cmb-panasas2/amalthom/software/genomes/species/Drosophila_melanogaster.BDGP6.22.97.chr.gtf"

Homo_sapiens_bed : "/panfs/cmb-panasas2/amalthom/software/genomes/species/Homo_sapiens.GRCh38.94.chr.bed"
Mus_musculus_bed: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Mus_musculus.GRCm38.94.chr.bed"
Gallus_gallus_bed : "/panfs/cmb-panasas2/amalthom/software/genomes/species/Gallus_gallus.Gallus_gallus-5.0.94.chr.bed"
Gorilla_gorilla_bed : "/panfs/cmb-panasas2/amalthom/software/genomes/species/Gorilla_gorilla.gorGor4.94.chr.bed"
Macaca_mulatta_bed: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Macaca_mulatta.Mmul_8.0.1.94.chr.bed"
Monodelphis_domestica_bed: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Monodelphis_domestica.monDom5.94.chr.bed"
Ornithorhynchus_anatinus_bed: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Ornithorhynchus_anatinus.OANA5.94.bed"
Pan_paniscus_bed: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Pan_paniscus.panpan1.1.94.chr.bed"
Pan_troglodytes_bed : "/panfs/cmb-panasas2/amalthom/software/genomes/species/Pan_troglodytes.Pan_tro_3.0.94.chr.bed"
Pongo_pygmaeus_bed: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Pongo_abelii.PPYG2.94.chr.bed"
Ciona_intestinalis_bed: "/auto/cmb-panasas2/amalthom/software/genomes/species/Ciona_intestinalis.KH.94.bed"
Danio_rerio_bed: "/auto/cmb-panasas2/amalthom/software/genomes/species/Danio_rerio.GRCz11.94.bed"
Sus_scrofa_bed: "/auto/cmb-panasas2/amalthom/software/genomes/species/Sus_scrofa.Sscrofa11.1.94.bed"
Tupaia_belangeri_bed: "/auto/cmb-panasas2/amalthom/software/genomes/species/Tupaia_belangeri.TREESHREW.94.bed"
Callithrix_jacchus_bed: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Callithrix_jacchus.ASM275486v1.94.bed"
Rattus_norvegicus_bed: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Rattus_norvegicus.Rnor_6.0.94.chr.bed"
Oryctolagus_cuniculus_bed: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Oryctolagus_cuniculus.OryCun2.0.94.bed"
Bos_taurus_bed: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Bos_taurus.UMD3.1.94.chr.bed"
Anolis_carolinensis_bed: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Anolis_carolinensis.AnoCar2.0.96.bed"
Xenopus_tropicalis_bed: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Tetraodon_nigroviridis.TETRAODON8.96.bed"
Tetraodon_nigroviridis_bed: "/panfs/cmb-panasas2/amalthom/software/genomes/species/Xenopus_tropicalis.JGI_4.2.96.bed"
Drosophila_melanogaster_bed: "/auto/cmb-panasas2/amalthom/software/genomes/species/Drosophila_melanogaster.BDGP6.22.97.chr.bed"

Anolis_carolinensis_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Anolis_carolinensis.AnoCar2.0.96.bed"
Bos_taurus_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Bos_taurus.UMD3.1.94.chr.bed"
Callithrix_jacchus_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Callithrix_jacchus.ASM275486v1.94.bed"
Ciona_intestinalis_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Ciona_intestinalis.KH.94.bed"
Danio_rerio_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Danio_rerio.GRCz11.94.bed"
Gallus_gallus_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Gallus_gallus.Gallus_gallus-5.0.94.chr.bed"
Gorilla_gorilla_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Gorilla_gorilla.gorGor4.94.chr.bed"
Homo_sapiens_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Homo_sapiens.GRCh38.94.chr.bed"
Macaca_mulatta_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Macaca_mulatta.Mmul_8.0.1.94.chr.bed"
Monodelphis_domestica_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Monodelphis_domestica.monDom5.94.chr.bed"
Mus_musculus_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Mus_musculus.GRCm38.94.chr.bed"
Ornithorhynchus_anatinus_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Ornithorhynchus_anatinus.OANA5.94.bed"
Oryctolagus_cuniculus_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Oryctolagus_cuniculus.OryCun2.0.94.bed"
Pan_paniscus_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Pan_paniscus.panpan1.1.94.chr.bed"
Pan_troglodytes_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Pan_troglodytes.Pan_tro_3.0.94.chr.bed"
Pongo_abelii_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Pongo_abelii.PPYG2.94.chr.bed"
Rattus_norvegicus_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Rattus_norvegicus.Rnor_6.0.94.chr.bed"
Sus_scrofa_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Sus_scrofa.Sscrofa11.1.94.bed"
Tetraodon_nigroviridis_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Tetraodon_nigroviridis.TETRAODON8.96.bed"
Tupaia_belangeri_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Tupaia_belangeri.TREESHREW.94.bed"
Xenopus_tropicalis_bed12: "/panfs/cmb-panasas2/amalthom/software/genomes/species/bed12/Xenopus_tropicalis.JGI_4.2.96.bed"
Drosophila_melanogaster_bed12: "/auto/cmb-panasas2/amalthom/software/genomes/species/bed12/Drosophila_melanogaster.BDGP6.22.97.chr.bed"
